name: insta-auto
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - fastapi=0.115.6
  - uvicorn=0.32.0
  - sqlalchemy=2.0.23
  - alembic=1.12.1
  - httpx=0.27.2
  - python-dotenv=1.0.1
  - pydantic=2.5.0
  - pip
  - pip:
    - aiosqlite==0.19.0
    - pydantic-settings==2.1.0
